// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package html

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "fmt"

func Counter(count int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Styles().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen bg-gradient-to-br from-purple-50 to-pink-100 flex items-center justify-center\"><div class=\"bg-white rounded-2xl shadow-2xl p-12 text-center max-w-md mx-4\"><div class=\"w-20 h-20 bg-purple-600 rounded-full flex items-center justify-center mx-auto mb-8\"><span class=\"text-3xl font-bold text-white\" id=\"count\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", count))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `html/counter.templ`, Line: 10, Col: 85}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></div><h2 class=\"text-2xl font-bold text-gray-800 mb-8\">カウンター</h2><div class=\"space-y-4\"><div class=\"flex gap-4 justify-center\"><button onclick=\"increment()\" class=\"w-16 h-16 bg-green-600 text-white rounded-full hover:bg-green-700 focus:ring-4 focus:ring-green-300 transition-all font-bold text-xl\">+</button> <button onclick=\"decrement()\" class=\"w-16 h-16 bg-red-600 text-white rounded-full hover:bg-red-700 focus:ring-4 focus:ring-red-300 transition-all font-bold text-xl\">-</button></div><button onclick=\"reset()\" class=\"w-full bg-gray-600 text-white py-3 px-6 rounded-lg hover:bg-gray-700 focus:ring-4 focus:ring-gray-300 transition-colors font-medium\">リセット</button> <a href=\"/\" class=\"block w-full bg-blue-600 text-white py-3 px-6 rounded-lg hover:bg-blue-700 transition-colors font-medium\">ホームに戻る</a></div></div></div><script>\r\n\t\tlet currentCount = ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3, templ_7745c5c3_Err := templruntime.ScriptContentOutsideStringLiteral(fmt.Sprintf("%d", count))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `html/counter.templ`, Line: 44, Col: 48}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ";\r\n\t\t\r\n\t\tfunction increment() {\r\n\t\t\tcurrentCount++;\r\n\t\t\tupdateDisplay();\r\n\t\t}\r\n\t\t\r\n\t\tfunction decrement() {\r\n\t\t\tcurrentCount--;\r\n\t\t\tupdateDisplay();\r\n\t\t}\r\n\t\t\r\n\t\tfunction reset() {\r\n\t\t\tcurrentCount = 0;\r\n\t\t\tupdateDisplay();\r\n\t\t}\r\n\t\t\r\n\t\tfunction updateDisplay() {\r\n\t\t\tdocument.getElementById('count').textContent = currentCount;\r\n\t\t}\r\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
